# Generated by Django 3.2.12 on 2022-03-23 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0006_classroom_parallesclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishingHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Издательство')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('edit_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата редактирования')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовать?')),
            ],
            options={
                'verbose_name': 'Издательство',
                'verbose_name_plural': 'Издательство',
            },
        ),
        migrations.CreateModel(
            name='TextBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('edit_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата редактирования')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовать?')),
                ('description', models.TextField(verbose_name='Описание')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='uploads/book/%Y/%m/%d/', verbose_name='Обложка')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Внешняя ссылка на учебник')),
                ('file', models.FileField(blank=True, help_text='загружать только pdf', null=True, upload_to='uploads/book/file/%Y/%m/%d/', verbose_name='Учебник для прикрепление')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.classroom', verbose_name='Класс')),
                ('publishingHouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publishingHouse.publishinghouse', verbose_name='Издательство')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Учебники',
                'verbose_name_plural': 'Учебники',
            },
        ),
    ]
