# Generated by Django 3.2.12 on 2022-03-23 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publishingHouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearPublising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Год издание')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('edit_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата редактирования')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовать?')),
            ],
            options={
                'verbose_name': 'Год издание',
                'verbose_name_plural': 'Год издание',
            },
        ),
        migrations.AddField(
            model_name='textbook',
            name='yearPublishing',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='publishingHouse.yearpublising', verbose_name='Год издание'),
            preserve_default=False,
        ),
    ]
