# Generated by Django 3.2.12 on 2022-03-23 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_classroom_parallesclass'),
        ('publishingHouse', '0002_auto_20220323_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbook',
            name='language',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='catalog.language', verbose_name='Язык'),
            preserve_default=False,
        ),
    ]
