# Generated by Django 3.2.12 on 2022-03-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishingHouse', '0003_textbook_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbook',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
