version: "3.5"
   
services:
  alternative_dev:
    build: .
    restart: always
    container_name: alternative-dev
    volumes:
      - ".:/projects/choice"
    ports:
      - "${PORT}:8000"
    environment:
      DEBUG: "True"
    networks:
      - https
      - database

networks:
  https:
    external:
      name: ${HTTPS_NETWORK}
  database:
    external:
      name: ${DATABASE_NETWORK}
