# Generated by Django 3.2.12 on 2022-03-23 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0006_classroom_parallesclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование организации')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('edit_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата редактирования')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовать?')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.district', verbose_name='Район')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.language')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.locality', verbose_name='Населенный пункт')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.region', verbose_name='Область')),
                ('territoriAlaffiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.territorialaffiliation', verbose_name='Территориральная принадлежность')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
    ]
