# Generated by Django 3.2.12 on 2022-03-23 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='full_name',
        ),
    ]
