# Generated by Django 3.2.12 on 2022-03-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_remove_teacherprofile_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='iin',
            field=models.IntegerField(verbose_name='ИИН'),
        ),
    ]
