# Generated by Django 3.2.12 on 2022-03-23 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publishingHouse', '0004_alter_textbook_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0006_classroom_parallesclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.classroom', verbose_name='Класс')),
                ('publishingHouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publishingHouse.publishinghouse', verbose_name='Издательство')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.subject', verbose_name='Предмет')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('yearPublishing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publishingHouse.yearpublising', verbose_name='Год издание')),
            ],
            options={
                'verbose_name': 'Выбранные учебники',
                'verbose_name_plural': 'Выбранные учебники',
            },
        ),
    ]
