# Generated by Django 3.2.12 on 2022-03-23 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Район')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('edit_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата редактирования')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовать?')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Язык')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('edit_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата редактирования')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовать?')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Область')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('edit_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата редактирования')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовать?')),
            ],
            options={
                'verbose_name': 'Область',
                'verbose_name_plural': 'Области',
            },
        ),
        migrations.CreateModel(
            name='TerritorialAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Область')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('edit_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата редактирования')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовать?')),
            ],
            options={
                'verbose_name': 'Территориральная принадлежность',
                'verbose_name_plural': 'Территориальные принадлежности',
            },
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Населенный пункт')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('edit_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата редактирования')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовать?')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.district', verbose_name='Область')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.region', verbose_name='Область')),
            ],
            options={
                'verbose_name': 'Населенный пункт',
                'verbose_name_plural': 'Населенные пункты',
            },
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.region', verbose_name='Область'),
        ),
    ]
