# Generated by Django 3.2.12 on 2022-03-23 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_district_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.district', verbose_name='Район'),
        ),
    ]
