# Generated by Django 3.2.12 on 2022-03-23 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20220323_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование предмета')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('edit_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата редактирования')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовать?')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.language', verbose_name='Язык обучение')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
    ]
